// sanity/schemas/blocks/shared/color-variant.ts
import { defineType } from "sanity";

export const COLOR_VARIANTS = [
  { title: "Background", value: "background" },
  { title: "Foreground", value: "foreground" },
  { title: "Card", value: "card" },
  { title: "Card Foreground", value: "card-foreground" },
  { title: "Popover", value: "popover" },
  { title: "Popover Foreground", value: "popover-foreground" },
  { title: "Primary", value: "primary" },
  { title: "Primary Foreground", value: "primary-foreground" },
  { title: "Secondary", value: "secondary" },
  { title: "Secondary Foreground", value: "secondary-foreground" },
  { title: "Muted", value: "muted" },
  { title: "Muted Foreground", value: "muted-foreground" },
  { title: "Accent", value: "accent" },
  { title: "Accent Foreground", value: "accent-foreground" },
  { title: "Destructive", value: "destructive" },
  { title: "Destructive Foreground", value: "destructive-foreground" },
  { title: "White", value: "white" },
  { title: "White Foreground", value: "white-foreground" },
  { title: "Black", value: "black" },
  { title: "Black Foreground", value: "black-foreground" },
  { title: "Light Gray", value: "light-gray" },
  { title: "Light Gray Foreground", value: "light-gray-foreground" },
  { title: "Cool Gray", value: "cool-gray" },
  { title: "Cool Gray Foreground", value: "cool-gray-foreground" },
  { title: "Soft Blue", value: "soft-blue" },
  { title: "Soft Blue Foreground", value: "soft-blue-foreground" },
  { title: "Sky Blue", value: "sky-blue" },
  { title: "Sky Blue Foreground", value: "sky-blue-foreground" },
  { title: "Mint", value: "mint" },
  { title: "Mint Foreground", value: "mint-foreground" },
  { title: "Sand", value: "sand" },
  { title: "Sand Foreground", value: "sand-foreground" },
  { title: "Peach", value: "peach" },
  { title: "Peach Foreground", value: "peach-foreground" },
  { title: "Slate", value: "slate" },
  { title: "Slate Foreground", value: "slate-foreground" },
  { title: "Navy", value: "navy" },
  { title: "Navy Foreground", value: "navy-foreground" },
  { title: "Charcoal", value: "charcoal" },
  { title: "Charcoal Foreground", value: "charcoal-foreground" },
];

export const colorVariant = defineType({
  name: "color-variant",
  title: "Color Variant",
  type: "string",
  options: {
    list: COLOR_VARIANTS.map(({ title, value }) => ({ title, value })),
  },
  initialValue: "background",
});
