// lib/icons.ts
// Re-export the lucide-react icons we actually use so the bundler only ships these symbols.
export {
  AlignRight,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  Eye,
  Heart,
  Copy,
  Minus,
  Plus,
  Loader2,
  CalendarDays,
  Mail,
  Menu,
  ShoppingCart,
  LayoutGrid,
  Rows,
  Moon,
  MoreHorizontal,
  Trash2,
  Star,
  StarHalf,
  Sun,
  X,
} from 'lucide-react';

export {
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  Circle as CircleIcon,
  Menu as MenuIcon,
  MoreHorizontal as MoreHorizontalIcon,
  X as XIcon,
} from 'lucide-react';
